[book]
title = "MarvinDocs v1.2.4"
authors = [
    "José G. C. Pereira",
    "João V. S. Guerra",
    "João V. R. Santos",
    "Luiz F. G. Alves",
    "Pablo W. A. Silva",
    "Rick H. Hokama",
    "Samuel C. de Assis"
]
description = "Documentação do HPCC Marvin"
src = "src"
language = "pt-br"
text-direction = "ltr"

[build]
build-dir = "book"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html.fold]
enable = true
