[book]
authors = [
    "José G. C. Pereira",
    "João V. S. Guerra",
    "Luiz F. G. Alves",
    "Pablo W. A. Silva"
]
src = "src"
title = "Marvin Docs"

[build]
build-dir = "book"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
