[book]
authors = [
    "Dr. José G. C. Pereira",
    "Dr. João V. S. Guerra",
    "MSc. Luiz F. G. Alves",
    "Pablo W. A. Silva"
]
language = "ptbr"
multilingual = true
src = "src"
title = "Marvin Docs"

[owner]
name = "LNBio|CNPEM"

[build]
build-dir = "book"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html.search]
limit-results = 15
