[book]
title = "MarvinDocs v1.0.0"
authors = [
    "José G. C. Pereira",
    "João V. S. Guerra",
    "Luiz F. G. Alves",
    "Pablo W. A. Silva"
]
description = "Documentação do HPCC Marvin"
src = "src"
language = "pt-br"
text-direction = "ltr"

[build]
build-dir = "book"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
