[package]
name = "MarvinDocs"
version = "0.3.1"
edition = "2021"
readme = "README.md"
license = "CC-BY-4.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdbook = "0.4.40"
mdbook-toc = "0.14.2"
mdbook-catppuccin = "3.0.0"
